CREATE DATABASE Insurance_company;
DELETE FROM DEPARTMENT;
DELETE FROM EMPLOYEE;
DELETE FROM CUSTOMER;
DELETE FROM POLICY;
DELETE FROM SERVICE;
DELETE FROM BENEFICIAR;
DELETE FROM INSURANCASE;
DELETE FROM PAYMENT;

CREATE TABLE DEPARTMENT(ID INT PRIMARY KEY NOT NULL, NAME VARCHAR(20), CITY VARCHAR(15));
CREATE TABLE EMPLOYEE(ID INT PRIMARY KEY NOT NULL, FIRSTNAME VARCHAR(30), LASTNAME VARCHAR(30), GENDER VARCHAR(1), PHONE_NUMBERS INT, POSITION VARCHAR(15), DATE_EMPLOYMENT DATE, ID_DEPARTMENT INT, RATE INT, BONUS INT);
CREATE TABLE CUSTOMER(ID INT PRIMARY KEY NOT NULL, FIRSTNAME VARCHAR(30),LASTNAME VARCHAR(30), GENDER VARCHAR(1), DATE_BIRTH DATE, PHONE_NUMBERS INT, EMAIL VARCHAR(30), DISCOUNT INT);
CREATE TABLE BENEFICIAR(ID INT PRIMARY KEY NOT NULL, FIRSTNAME VARCHAR(30),LASTNAME VARCHAR(30), GENDER VARCHAR(1), DATE_BIRTH DATE, PHONE_NUMBERS INT, EMAIL VARCHAR(30));
CREATE TABLE SERVICE( ID INT PRIMARY KEY NOT NULL, PRODUCT_NAME VARCHAR(30), PRODUCT_DESCRIPTION VARCHAR(30), PRODUCT_TYPE VARCHAR(15), PRICE FLOAT); 
CREATE TABLE POLICY(ID INT PRIMARY KEY NOT NULL, NUMBER INT, SERVICE_ID INT, EMPLOYEE_ID INT, CUSTOMER_ID INT, BENEFICIAR_ID INT, INSURANCASE_ID INT, TRANSACTION_TYPE VARCHAR(15), DATE_START DATE,DATE_END DATE, AMOUNT INT);
CREATE TABLE INSURANCASE(ID INT PRIMARY KEY NOT NULL, NAME VARCHAR(20), PAYMENT_PERCENT INT);
CREATE TABLE PAYMENT(ID INT PRIMARY KEY NOT NULL, INSURANCASE_ID INT, POLICY_ID INT, DATE_INSURANCASE DATE, DATE_PAYMENT DATE);

USE Insurance_company;

ALTER TABLE POLICY ADD FOREIGN KEY(SERVICE_ID) REFERENCES SERVICE(ID);
ALTER TABLE EMPLOYEE ADD FOREIGN KEY(ID_DEPARTMENT) REFERENCES DEPARTMENT(ID);
ALTER TABLE POLICY ADD FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(ID);
ALTER TABLE POLICY ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID);
ALTER TABLE POLICY ADD FOREIGN KEY(BENEFICIAR_ID) REFERENCES BENEFICIAR(ID);
ALTER TABLE PAYMENT ADD FOREIGN KEY(INSURANCASE_ID) REFERENCES INSURANCASE(ID);
ALTER TABLE PAYMENT ADD FOREIGN KEY(POLICY_ID) REFERENCES POLICY(ID);

ALTER TABLE POLICY DROP COLUMN NUMBER;
ALTER TABLE POLICY ADD OVERPAY INT;
ALTER TABLE POLICY DROP COLUMN AMOUNT;
ALTER TABLE POLICY ADD DESCRIPTION INT;
ALTER TABLE POLICY DROP COLUMN DESCRIPTION;
ALTER TABLE POLICY ADD DESCRIPTION VARCHAR(50);
ALTER TABLE PAYMENT ADD AMOUNT INT;
ALTER TABLE SERVICE DROP COLUMN PRODUCT_DESCRIPTION;
ALTER TABLE SERVICE ADD PRODUCT_DESCRIPTION VARCHAR(100);
ALTER TABLE POLICY DROP COLUMN INSURANCASE_ID;
ALTER TABLE PAYMENT DROP COLUMN AMOUNT;


INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (1, 'Personal insurance', 'Lviv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (2, 'Property insurance', 'Lviv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (3, 'Travel insurance', 'Lviv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (4, 'Personal insurance', 'Kiyv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (5, 'Property insurance', 'Kiyv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (6, 'Travel insurance', 'Kiyv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (7, 'Personal insurance', 'Rivne');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (8, 'Property insurance', 'Rivne');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (9, 'Travel insurance', 'Rivne');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (10, 'Accounting', 'Lviv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (11, 'Marketing and PR', 'Kyiv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (12, 'Administration', 'Lviv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (13, 'Support and IT', 'Kyiv');
INSERT INTO DEPARTMENT(ID, NAME, CITY) VALUES (14, 'Legal', 'Kyiv');

SELECT * FROM department;

INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (1, 'Yaskiv', 'Anton', 'Chairman rude', '1998/10/11', 12, 30000, 2000, 'm', 0675437253);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (2, 'Melnyk', 'Olga', 'Deputy Chairman', '2011/03/09', 12, 27500, NULL, 'w', 0936573283);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (3, 'Kovalenko', 'Taras', 'CEO', '2008/04/15', 12, 25000, NULL, 'm', 0507659345);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (4, 'Olijnyk', 'Vasyl', 'Deputy CEO', '2010/11/25', 12, 22000, 500, 'm', 0506683494);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (5, 'Bondar', 'Orest', 'Commercial Dr', '2005/06/22', 12, 25000, NULL, 'm', 0968457565);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (6, 'Rudenko', 'Igor', 'Dr Claim Loss', '2006/04/11', 12, 26500, NULL, 'm', 0968867565);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (7, 'Pavlenko', 'Lesya', 'Assistant', '2004/04/14', 12, 14000, NULL, 'w', 0684528309);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (8, 'Savchuk', 'Oleg', 'Secretary', '1996/09/28', 12, 13000, NULL, 'w', 0684528234);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (9, 'Lysenko', 'Vasyl', 'Secretary', '2015/10/01', 12, 13000, NULL, 'w', 0684657234);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (10, 'Olijnyk', 'Iryna', 'Head of the IT', '2003/01/05', 13, 23000, NULL, 'w', 0685467374);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (11, 'Kravchuk', 'Myron', 'Systym admin', '2015/07/17', 13, 21000, NULL, 'm', 0986571232);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (12, 'Savchenko', 'Mariya', 'Site editor', '2012/10/03', 13, 21000, NULL, 'w', 093457273);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (13, 'Shkil', 'Oleg', 'Database admin', '2001/08/24', 13, 21000, 1500, 'm', 0685647327);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (14, 'Maslyanko', 'Bogdan', 'Consultant', '2009/08/30', 13, 20000, NULL, 'm', 0965478765);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (15, 'Kyrychenko', 'Vasylyna', 'Consultant', '2013/09/18', 13, 20000, NULL, 'w', 0675647437);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (16, 'Kryvonis', 'Myron', 'Loss specialist', '2000/05/11', 10, 15000, 750, 'm', 0663545436);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (17, 'Semenyuk', 'Andrij', 'Loss specialist', '2024/10/07', 10, 15000, 750, 'm', 0638758754);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (18, 'Yarmolyuk', 'Oleksandra', 'HR specialist', '2003/12/02', 10, 13000, NULL, 'w', 0675437485);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (19, 'Shevchenko', 'Anton', 'HR specialist', '2003/01/09', 10, 13000, NULL, 'm', 0957478778);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (20, 'Goncharenko', 'Vasyl', 'Checker', '1999/08/16', 10, 11000, NULL, 'm', 0975463377);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (21, 'Shubert', 'Igor', 'Checker', '2015/03/11', 10, 11000, NULL, 'm', 0987650981);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (22, 'Mykailskyi', 'Bohdan', 'Ch accounting', '2001/02/02', 10, 19000, NULL, 'm', 0986543282);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (44, 'Sysuk', 'Oleh', 'Accounting', '2002/06/29', 10, 15000, NULL, 'm', 0984356543);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (23, 'Porodko', 'Max', 'Accounting', '1999/11/24', 10, 15000, 1000, 'm', 0986576583);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (24, 'Romanchyshyn', 'Oleh', 'Accounting', '2015/03/11', 10, 15000, NULL, 'm', 0986987382);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (25, 'Melnyk', 'Hanna', 'Financier', '2001/12/17', 10, 16000, NULL, 'w', 0506987382);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (26, 'Tymkiv', 'Khrystyna', 'Chief marketer', '1998/06/15', 11, 15500, NULL, 'w', 0506987382);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (27, 'Kaniy', 'Andriy', 'Marketer', '1990/10/10', 11, 14000, NULL, 'm', 0506928576);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (28, 'Kalyta', 'Yaroslav', 'Marketer', '2000/01/30', 11, 14000, NULL, 'm', 0953748374);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (29, 'Yartym', 'Ivan', 'SMM-manager', '2007/10/07', 11, 14000, NULL, 'm', 0509873452);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (30, 'Kobryn', 'Yuriy', 'SMM-manager', '2009/10/05', 11, 14000, NULL, 'm', 0506098712);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (31, 'Dobosewych', 'Danylo', 'Net-manager', '2021/05/26', 11, 14000, NULL, 'm', 0638769871);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (32, 'Kryvinskiy', 'Yuriy', 'Content-manager', '2018/08/03', 11, 14000, NULL, 'm', 0937489874);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (33, 'Salabay', 'Yuriy', 'Head of legal', '1998/09/24', 14, 19000, NULL, 'm', 0907389838);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (34, 'Diakiv', 'Serhiy', 'Lawyer', '2001/11/13', 14, 15000, NULL, 'm', 0974567309);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (35, 'Didukh', 'Anna', 'Lawyer', '2000/03/01', 14, 15000, NULL, 'w', 0978759090);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (36, 'Didukh', 'Tetyana', 'Lawyer', '1998/12/05',  14, 15000, NULL, 'w', 0967589857);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (37, 'Dembitska', 'Ilona', 'Notary', '2000/04/20', 14, 15000, 500, 'w', 0932349874);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS)  
	VALUES (38, 'Chaplia', 'Maria', 'Notary', '2003/07/13',  14, 15000, NULL, 'w', 0932323421);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (39, 'Ponomarchuk', 'Lyudmyla', 'Notary', '1999/03/08',  14, 15000, 1000, 'w', 0932394872);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (40, 'Shyika', 'Roman', 'Head', '2002/06/12', 1, 18000, NULL, 'm', 0932323421);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (41, 'Fedorchak', 'Vitaliy', 'Head', '1987/07/10', 2, 18000, NULL, 'm', 0932323421);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (42, 'Lutchyn', 'Dmytro', 'Head', '1997/11/30', 3, 18000, NULL, 'm', 0956789482);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (43, 'Procyk', 'Nazar', 'Head', '1980/03/15', 4, 18000, NULL, 'm', 0997658454);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (45, 'Savka', 'Halyna', 'Head', '2014/01/21', 5, 18000, NULL, 'w', 0975467283);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (46, 'Protasar', 'Nazar', 'Head', '2010/03/15', 6, 18000, NULL, 'm', 0986570948);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (47, 'Lishyk', 'Mia', 'Head', '2021/06/30', 9, 18000, NULL, 'w', 0669871230);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (48, 'Topolya', 'Ostap', 'Head', '2019/10/17', 7, 18000, NULL, 'm', 0932323234);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (49, 'Karpchuk', 'Natalia', 'Head', '2009/09/19', 8, 18000, NULL, 'w', 0932320921);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (50, 'Zotov', 'Anastasia', 'Manager', '2002/02/02', 1, 11500, NULL, 'w', 0993478551);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (51, 'Prokipenko', 'Natalia', 'Insurer', '2002/01/19', 1, 12000, NULL, 'w', 0685648391);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (52, 'Panas', 'Volodymyr', 'Insurer', '2021/08/23', 1, 12000, NULL, 'm', 0969720876);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (53, 'Matsiv', 'Dmytro', 'Insurer', '2018/07/13', 1, 12000, NULL, 'm', 0508764329);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (54, 'Lomyk', 'Yulia', 'Insurer', '2020/11/13', 1, 12000, NULL, 'w', 0969720872);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (55, 'Kiprak', 'Stefania', 'Manager', '2022/02/02', 2, 11500, NULL, 'w', 0993478551);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (56, 'Pfilyk', 'Semen', 'Insurer', '2022/04/19', 2, 12000, NULL, 'm', 0685648391);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (57, 'Panchyshyn', 'Oleg', 'Insurer', '2021/05/19', 2, 12000, NULL, 'm', 0969720876);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (58, 'Matvisiv', 'Stanislav', 'Insurer', '2019/09/17', 2, 12000, NULL, 'm', 0508764329);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (59, 'Rabotynska', 'Yulia', 'Insurer', '2021/10/17', 2, 12000, NULL, 'w', 0969720872);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (60, 'Kiprak', 'Stefania', 'Manager', '2019/01/12', 3, 11500, NULL, 'w', 0993909871);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (61, 'Pfilyk', 'Semen', 'Insurer', '2018/04/29', 3, 12000, NULL, 'm', 0685640985);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (62, 'Panchyshyn', 'Oleg', 'Insurer', '2020/05/05', 3, 12000, NULL, 'm', 0954320876);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (63, 'Mastkyla', 'Stanislav', 'Insurer', '2017/09/21', 3, 12000, NULL, 'm', 0508709539);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (64, 'Rabotynska', 'Yulia', 'Insurer', '2018/12/14', 3, 12000, NULL, 'w', 0969709812);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (65, 'Khreptyk', 'Oleksandra', 'Manager', '2016/01/12', 4, 11500, NULL, 'w', 0993909675);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (66, 'Antonenko', 'Andriy', 'Insurer', '2021/06/20', 4, 12000, NULL, 'm', 0685948585);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (67, 'Palamar', 'Max', 'Insurer', '2018/12/05', 4, 12000, NULL, 'm', 0954320985);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (68, 'Matvisiv', 'Svyatoslav', 'Insurer', '2021/07/15', 4, 12000, NULL, 'm', 0508709949);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (69, 'Polybotko', 'Ivanka', 'Insurer', '2018/12/14', 4, 12000, NULL, 'w', 0969765729);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (70, 'Koval', 'Lidia', 'Manager', '2015/08/30', 5, 11500, NULL, 'w', 0669870797);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (71, 'Kovalenko', 'Inna', 'Insurer', '2018/01/20', 5, 12000, NULL, 'w', 0668739391);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (72, 'Stepanenko', 'Volodymyr', 'Insurer', '2020/07/28', 5, 12000, NULL, 'm', 0979420876);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (73, 'Lisnyk', 'Dmytro', 'Insurer', '2018/07/13', 5, 12000, NULL, 'm', 0508709859);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (74, 'Libryk', 'Yulianna', 'Insurer', '2016/10/31', 5, 12000, NULL, 'w', 0956734872);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (82, 'Zotova', 'Oksana', 'Manager', '2022/01/04', 6, 11500, NULL, 'w', 099096551);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (75, 'Notova', 'Halyna', 'Insurer', '2019/09/19', 6, 12000, NULL, 'w', 0680981231);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (76, 'Hnativ', 'Ivan', 'Insurer', '2011/12/23', 6, 12000, NULL, 'm', 0969720954);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (77, 'Semen', 'Yaroslav', 'Insurer', '2019/09/13', 6, 12000, NULL, 'm', 0508798229);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (78, 'Veselova', 'Lyudmyla', 'Insurer', '2020/05/13', 6, 12000, NULL, 'w', 096223342);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (79, 'Zotov', 'Anastasia', 'Manager', '2022/02/02', 7, 11500, NULL, 'w', 0993098454);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (80, 'Bukhanysta', 'Valentyna', 'Insurer', '2022/03/20', 7, 12000, NULL, 'w', 0685093491);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (81, 'Knysh', 'Oleksandr', 'Insurer', '2018/09/02', 7, 12000, NULL, 'm', 0969234876);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (83, 'Ustymenko', 'Andriy', 'Insurer', '2016/07/20', 7, 12000, NULL, 'm', 0508709456);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (84, 'Dobrovska', 'Maria', 'Insurer', '2021/11/01', 7, 12000, NULL, 'w', 0969792372);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (85, 'Melnyk', 'Lydmyla', 'Manager', '2012/10/02', 8, 11500, NULL, 'w', 0997648743);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (86, 'Maksymova', 'Olena', 'Insurer', '2021/09/05', 8, 12000, NULL, 'w', 0685609874);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (87, 'Lukashov', 'Vladyslav', 'Insurer', '2018/10/20', 8, 12000, NULL, 'm', 0969798723);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (88, 'Polyshko', 'Dmytro', 'Insurer', '2019/06/10', 8, 12000, NULL, 'm', 0508094229);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (89, 'Kolomytsina', 'Kateryna', 'Insurer', '2021/09/19', 8, 12000, NULL, 'w', 0969103872);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (90, 'Bila', 'Tetyana', 'Manager', '2021/09/21', 9, 11500, NULL, 'w', 0993340812);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (91, 'Skachok', 'Olena', 'Insurer', '2020/03/07', 9, 12000, NULL, 'w', 0685693391);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (92, 'Hrydko', 'Volodymyr', 'Insurer', '2015/09/23', 9, 12000, NULL, 'm', 0969734093);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (93, 'Fedorov', 'Dmytro', 'Insurer', '2019/09/03', 9, 12000, NULL, 'm', 0508093329);
INSERT INTO EMPLOYEE (ID, LASTNAME, FIRSTNAME, POSITION, DATE_EMPLOYMENT, ID_DEPARTMENT, RATE, BONUS, GENDER, PHONE_NUMBERS) 
	VALUES (94, 'Isava', 'Anastasia', 'Insurer', '2020/11/13', 9, 12000, NULL, 'w', 0969729234);

SELECT * FROM EMPLOYEE;

INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(1, 'Schypanska', 'Anastasia', 'w', '2000/12/09', 0978464164, 'a.shypanska@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(2, 'Maletych', 'Roksolana', 'w', '2007/05/20', 0984579824, 'r.maletych@gmail.com', 5);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(3, 'Mokshyn', 'Artem', 'm', '1990/06/10', 0634875421, 'a.mksn@outlook.com', 10);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(4, 'Bereziak', 'Sophia', 'w', '2001/07/21', 0635213432, 'sophiaber@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(5, 'Panas', 'Yulia', 'w', '2004/03/04', 0964567841, 'y.panas@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(6, 'Oleniak', 'Nazar', 'm', '2001/08/15', NULL, NULL, NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(7, 'Filaret', 'Victoria', 'w', '2001/10/26', 0504785212, 'vfilerat@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(8, 'Leskiv', 'Yaroslav', 'm', '1998/09/04', 0504784875, NULL, NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(9, 'Kozura', 'Nazariy', 'm', '1995/02/21', 0765482125, 'kozuuuur@outlook.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(10, 'Fedak', 'Andriy', 'm', '1999/07/04', NULL, 'fedaka@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(11, 'Khorkava', 'Yulia', 'w', '2004/11/30', 0634564512, 'y.khorkava@gmail.com', 10);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(12, 'Melnechuk', 'Viktoria', 'w', '2004/09/24', 0678945768, 'vikamel@outlook.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(13, 'Efremchuk', 'Uliana', 'w', '1994/02/26', 0675846556, NULL, 5);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(14, 'Procurat', 'Viktoria', 'w', '2003/12/25', 0674859854, 'victoriiapr@gmail.com', 10);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(15, 'Melenchuk', 'Ihor', 'm', '1996/03/14', 0501236552, 'ihor.melen@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(16, 'Sitar', 'Andriy', 'm', '1986/04/28', 0735665478, 'a.sitar@gmail.com', 5);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(17, 'Yakovenko', 'Dmytro', 'm', '1998/04/27', 0634523665, 'yakondm@gmail.com', 5);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(18, 'Marin', 'Danyil', 'm', '2003/07/08', 0978457848, 'danmarin@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(19, 'Mackevych', 'Andriana', 'w', '2002/09/14', 0735458785, NULL, NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(20, 'Yakymets', 'Uliana', 'w', '2001/10/20', 0635444787, 'uliana.yakymets@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(21, 'Borcsh', 'Maria', 'w', '2003/11/13', 0984562454, 'mbor@outlook.com', 5);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(22, 'Chyg', 'Danylo', 'm', '2001/11/09', 0998456457, 'danyachyg@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(23, 'Soroka', 'Lev', 'm', '2002/09/18', 0984562454, NULL, 5);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(24, 'Vovk', 'Dmytriy', 'm', '2001/05/13', 0965892145, 'vovkdm@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT) 
          VALUES(25, 'Ogonovska', 'Anna', 'w', '1994/09/21', 0632586421, 'annaogon@outlook.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(26, 'Lahmanets', 'Khrystyna', 'w', '2004/06/03', 0965411224, NULL, NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(27, 'Pavlyk', 'Ivan', 'm', '1996/05/30', 0509784547, 'ivanpanlyk@gmail.com', 10);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(28, 'Voloshchuk', 'Victoria', 'w', '2000/02/28', NULL, 'victoriavoloshch@gmail.com', NULL);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(29, 'Onysko', 'Mykhailo', 'm', '1998/08/12', 0503665989, NULL, 5);
INSERT INTO CUSTOMER (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL, DISCOUNT)
          VALUES(30, 'Kit', 'Illya', 'm', '2003/07/19', 0965484514, 'illyakit@gmail.com', NULL);

select * from customer;

INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (1, 'For active tourists', 'Lost luggage at the airport, treatment of injuries, hospitalization, surgery', 'Travel', 500);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (2, 'For athletes', 'treatment of injuries, hospitalization, surgery, illness, disability', 'Travel', 500);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (3, 'For employees', 'diagnosis, treatment, medical evacuation, repatriation', 'Travel', 450);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (4, 'For business trips', 'lost luggage at the airport, flight rescheduling, injury treatment, hospitalization, surgery', 'Travel', 550);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (7, 'For houses, apartment, flat', 'fires, natural disasters, floods, theft', 'Property', 16500);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (5, 'For land', 'fires, natural disasters, floods', 'Property', 8000);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (6, 'For appliances', 'fires, natural disasters, floods, theft, breaking', 'Property', 10000);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (8, 'Autocivil', 'traffic accident, natural disaster, illegal possession, fire, explosion, illegal actions', 'Property', 8000);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (9, 'CASCO Small', 'traffic accident, natural disaster, illegal possession, fire, explosion, illegal actions', 'Property', 10000);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (10, 'CASCO Large', 'limit of UAH 25,000, traffic accident, natural disaster, illegal possession, ets', 'Property', 14000);         
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (11, 'Health', 'injuries, surgery, hospitalization, illness, disability, critical illness, poisoning', 'Personal', 150000);
INSERT INTO SERVICE (ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_TYPE, PRICE)
		  VALUES (12, 'Life', 'any cause of death other than suicide', 'Personal', 180000);   
          
select * from service;
          
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (1,'death', 90);   
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (2,'hospitalization', 55);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (3,'diagnosis', 40);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (4,'treatment', 45);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (5,'surgery', 75);   
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (6,'disability 1-2', 90);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (7,'disability 3', 75);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (8,'critical illness', 95);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (9,'poisoning', 45);   
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (10,'road accident', 70);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (11,'luggage loss', 65);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (12,'flight rescheduling', 25);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (13,'natural disaster', 70);   
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (14,'breakdown', 50);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		  VALUES (15,'theft', 80);  
INSERT INTO INSURANCASE(ID, NAME, PAYMENT_PERCENT)
		VALUES (16,'illegal actions', 70);  
        
select * from insurancase;

INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(1, 'Schypanska', 'Anastasia', 'w', '2000/12/09', 0978464164, 'a.shypanska@gmail.com' );
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(2, 'Maletych', 'Roksolana', 'w', '2007/05/20', 0984579824, 'r.maletych@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(3, 'Mokshyn', 'Artem', 'm', '1990/06/10', 0634875421, 'a.mksn@outlook.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(4, 'Bereziak', 'Sophia', 'w', '2001/07/21', 0635213432, 'sophiaber@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(5, 'Panas', 'Yulia', 'w', '2004/03/04', 0964567841, 'y.panas@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(6, 'Oleniak', 'Nazar', 'm', '2009/08/15', NULL, NULL);
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(7, 'Filaret', 'Victoria', 'w', '2001/10/26', 0504785212, 'vfilerat@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(8, 'Leskiv', 'Yaroslav', 'm', '1998/09/04', 0504784875, NULL);
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(9, 'Kozura', 'Nazariy', 'm', '1995/02/21', 0765482125, 'kozuuuur@outlook.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(10, 'Fedak', 'Andriy', 'm', '1999/07/04', NULL, 'fedaka@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(11, 'Khorkava', 'Yulia', 'w', '2004/11/30', 0634564512, 'y.khorkava@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(12, 'Melnechuk', 'Viktoria', 'w', '2004/09/24', 0678945768, 'vikamel@outlook.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(13, 'Efremchuk', 'Uliana', 'w', '1994/02/26', 0675846556, NULL);
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(14, 'Procurat', 'Viktoria', 'w', '2003/12/25', 0674859854, 'victoriiapr@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(15, 'Melenchuk', 'Ihor', 'm', '1996/03/14', 0501236552, 'ihor.melen@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(16, 'Sitar', 'Andriy', 'm', '1986/04/28/', 0735665478, 'a.sitar@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(17, 'Yakovenko', 'Dmytro', 'm', '1998/04/27', 0634523665, 'yakondm@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(18, 'Marin', 'Danyil', 'm', '2006/07/08', 0978457848, 'danmarin@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(19, 'Mackevych', 'Andriana', 'w', '2002/09/14', 0735458785, NULL);
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(20, 'Yakymets', 'Uliana', 'w', '2005/10/20', 0635444787, 'uliana.yakymets@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(21, 'Borcsh', 'Dmytro', 'm', '2000/01/04', 0963459870, 'dm.borcsh@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(22, 'Chyg', 'Oksana', 'w', '1980/06/09', 0998458794, 'oksanachyg@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(23, 'Marin', 'Danylo', 'm', '2002/09/30', 0984876094, NULL);
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(24, 'Vovk', 'Victoria', 'w', '2003/02/10', 0960813145, 'vovk@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(25, 'Ogonovska', 'Maria', 'w', '2012/09/12', 0632586549, NULL);
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(26, 'Lahmanets', 'Andriy', 'm', '1980/10/29', 0965465980, NULL);
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(27, 'Pavlyk', 'Yulia', 'w', '1999/04/05', 0509798457, 'yu.vanpanlyk@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(28, 'Tatasenko', 'Vita', 'w', '2005/12/20', NULL, 'vitochka@gmail.com');
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(29, 'Onysko', 'Halyna', 'w', '1999/09/30', 0503679349, NULL);
INSERT INTO BENEFICIAR (ID, LASTNAME, FIRSTNAME, GENDER, DATE_BIRTH, PHONE_NUMBERS, EMAIL)
          VALUES(30, 'Kit', 'Taras', 'm', '2000/07/07', 0989354514, 'taraskit@gmail.com');
          
select * from beneficiar;
          
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (1, 1, 52, 1, 1, 'cash', '2022/03/20', '2022/04/20', 3000, 'Trip to France');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (2, 5, 93, 5, 5, 'card', '2021/08/02', '2022/08/02', 1000, 'House on the outskirt of the city 300 sq m');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (3, 3, 55, 7, 7, 'cash', '2022/01/07', '2022/02/17', 3000, 'Work in Germany');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (4, 8, 77, 11, 11, 'card', '2021/04/10', '2022/04/10', 2000, 'Volkswagen golf, BC2002HO, 2009, experience 7');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (5, 10, 82, 9, 9, 'cash', '2022/05/06', '2023/05/06', 14000, 'BMW x5, BA0082OM, 2013, experience 4');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (6, 11, 63, 17, 17, 'cash', '2022/03/10', '2023/03/10', 2000, NULL);
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (7, 5, 51, 21, 21, 'cash', '2021/09/15', '2022/09/15', 120000, 'Apartment in the city center 100 sq m');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (8, 7, 88, 27, 27, 'card', '2021/10/20', '2021/04/20', 4000, 'Musical equipment');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (9, 2, 94, 23, 23, 'card', '2022/05/15', '2022/05/25', 600, 'Trip to Poland');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (10, 6, 86, 30, 30, 'card', '2022/01/28', '2022/04/28', 5000, 'Land in the village');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (11, 9, 69, 29, 29, 'card', '2021/08/10', '2022/08/10', 1000, 'Audi A8, AI9928HP, 2016, experience 9');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (12, 3, 76, 5, 5, 'cash', '2021/07/12', '2021/01/07', 1500, 'Work in Turin');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (13, 7, 77, 3, 3, 'card', '2022/01/20', '2022/05/20', 2000, 'Medical equipment');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (14, 4, 54, 19, 19, 'cash', '2022/08/05', '2022/08/06', 1200, 'Business trip to Munich');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (15, 9, 58, 15, 15, 'card', '2022/05/19', '2023/05/19', NULL, 'Kia sorento, BE4832BB, 2017, experience 6');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (16, 2, 57, 17, 17, 'card', '2022/04/30', '2022/05/30', 1000, 'Trip to Italy');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (17, 6, 59, 8, 8, 'cash', '2022/03/02', '2022/08/02', 2000, 'Land in the village');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (18, 9, 68, 10, 10, 'card', '2022/05/15', '2023/05/15', 3000, 'Opel astra, CA3090IA, 2014, experience 12');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (19, 10, 72, 13, 13, 'card', '2022/02/09', '2023/02/09', 3000, 'Hyundai sonata, AX7712CA, 2015, experience 9');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (20, 11, 75, 12, 12, 'cash', '2022/04/15', '2023/04/15', 1500, NULL);
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (21, 5, 87, 16, 16, 'cash', '2022/01/27', '2023/01/27', 20000, 'Apartment in the city 75 sq m');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (22, 8, 92, 2, 2, 'card', '2022/01/21', '2023/01/21', NULL, 'Renault captur, BH8112KL, 2012, experience 8');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (23, 6, 91, 4, 4, 'cash', '2022/03/19', '2023/03/19', 1000, 'Land in the village');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (24, 3, 56, 6, 16, 'cash', '2021/10/17', '2021/10/20', NULL, 'Work in Poland');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (25, 6, 59, 14, 14, 'card', '2022/01/19', '2023/01/19', 1500, 'Land in the village');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (26, 1, 63, 18, 18, 'cash', '2022/02/14', '2022/02/24', 500, 'Trip to Antalya');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (27, 2, 73, 20, 20, 'card', '2022/04/10', '2022/04/12', NULL, 'Sports competitions in Turkey');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (28, 5, 76, 3, 3, 'cash', '2022/05/21', '2023/05/21', 7000, 'House on the outskirt of the city 350 sq m');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (29, 7, 83, 2, 2, 'card', '2022/05/08', '2022/05/09', NULL, 'Refrigeration equipment');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (30, 8, 86, 8, 8, 'cash', '2022/05/15', '2023/05/15', 1500, 'Mercedes Benz, BC3328KJ, 2006, experience 15');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (31, 3, 93, 10, 10, 'cash', '201/04/16', '2021/04/20', NULL, 'Work in Belgium');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (32, 9, 59, 1, 1, 'cash', '2022/02/28', '2023/02/28', 1000, 'Toyota Camry, AE6289KI, 2013, experience 8');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (33, 12, 75, 23, 23, 'card', '2022/03/30', '2023/03/30', 10000, NULL);
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (34, 11, 89, 1, 1, 'card', '2021/10/02', '2022/10/02', NULL, NULL);
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (35, 12, 87, 26, 26, 'cash', '2022/02/21', '2023/02/21', NULL, NULL);
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (36, 9, 52, 22, 22, 'cash', '2021/08/30', '2022/08/30', 2000, 'Nissan Liaf, BA4227CD, 2019, experience 11');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (37, 5, 58, 24, 24, 'cash', '2022/03/06', '2023/03/06', 22000, 'Land in the village');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (38, 9, 74, 25, 25, 'card', '2022/05/17', '2023/05/17', NULL, 'Nissan Liaf, BA0978CD, 2015, experience 2');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (39, 6, 78, 28, 28, 'card', '2022/06/03', '2023/06/03', 9000, 'Land in the village');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (40, 2, 83, 29, 29, 'cash', '2022/05/18', '2023/05/23', NULL, 'Sports competitions in Krakow');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (41, 2, 69, 19, 19, 'card', '2022/02/02', '2022/02/10', 150, 'Sports competitions in Porto');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (42, 3, 91, 20, 20, 'cash', '2022/04/07', '2022/04/17', 500, 'Work in Switzerland');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (43, 9, 72, 29, 29, 'card', '2022/01/12', '2023/01/12', NULL, 'Toyota Corola, AE6276HE, 2015, experience 5');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (44, 4, 88, 15, 15, 'cash', '2021/09/22', '2022/09/30', 200, 'Business trip to Barselona');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (45, 2, 66, 6, 6, 'cash', '2022/02/09', '2022/02/19', 600, 'Sports competitions in Rotterdam');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (46, 7, 82, 7, 7, 'cash', '2021/11/29', '2022/11/29', 15000, 'Medical equipment');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (47, 12, 58, 22, 22, 'card', '2021/04/20', '2023/04/20', NULL, NULL);
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (48, 10, 61, 2, 2, 'card', '2022/02/09', '2023/02/09', 3000, 'Opel Astra, AA3010IA, 2016, experience 2');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (49, 9, 84, 8, 8, 'cash', '2021/06/09', '2022/09/17', NULL, 'BMW x5, BA0348KM, 2014, experience 4');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (50, 4, 67, 30, 30, 'cash', '2022/01/04', '2023/01/04', 5000, 'Business trip to Viena');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (51, 1, 77, 15, 15, 'card', '2021/02/22', '2022/03/02', NULL, 'Trip to Milan');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (52, 8, 54, 18, 18, 'card', '2022/04/28', '2023/04/28', 2000, 'Audi A6, AI9018KO, 2018, experience 7');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (53, 6, 73, 26, 26, 'cash', '2022/05/21', '2023/05/21', NULL, 'Land in the village');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (54, 3, 81, 27, 27, 'cash', '2021/04/05', '2021/05/30', NULL, 'Work in Basel');
INSERT INTO POLICY (ID, SERVICE_ID, EMPLOYEE_ID, CUSTOMER_ID, BENEFICIAR_ID, TRANSACTION_TYPE, DATE_START, DATE_END, OVERPAY, DESCRIPTION)
     VALUES (55, 12, 83, 29, 29, 'cash', '2022/05/20', '2023/05/20', NULL, NULL);
     
select * from policy;
     
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (1, 5, 1, '2022/03/27', '2022/04/20');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (2, 8, 24, '2021/10/19', '2021/10/30');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (3, 14, 8, '2022/03/27', '2022/04/10');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (4, 16, 10, '2022/03/25', '2022/04/20');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (5, 1, 33, '2022/05/02', '2022/05/20');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (6, 13, 36, '2021/12/27', '2022/01/05');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (7, 5, 40, '2022/05/24', '2022/05/27');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (8, 16, 44, '2022/03/13', '2022/04/10');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (9, 14, 49, '2021/08/24', '2021/09/20');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (10, 4, 51, '2021/04/19', '2022/05/15');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (11, 11, 52, '2022/05/09', '2022/05/20');
INSERT INTO PAYMENT(ID, INSURANCASE_ID, POLICY_ID, DATE_INSURANCASE, DATE_PAYMENT)
     VALUES (12, 6, 54, '2021/05/11', '2021/06/13');
     
select * from payment;

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;
SELECT * FROM CUSTOMER;
SELECT * FROM SERVICE;
SELECT * FROM POLICY;
SELECT * FROM BENEFICIAR;
SELECT * FROM INSURANCASE;
SELECT * FROM PAYMENT;

//1. Показати прізвище та імя клієнта, назву послуги та дату початку полісу за 1 квартал 2022 р. Відсорт за ID полісу;
SELECT CUSTOMER.LASTNAME, CUSTOMER.FIRSTNAME, SERVICE.PRODUCT_NAME, POLICY.DATE_START
FROM POLICY, CUSTOMER, SERVICE
WHERE CUSTOMER_ID=CUSTOMER.ID 
AND SERVICE_ID=SERVICE.ID
AND DATE_START BETWEEN '2022/01/30' AND '2022/04/01'
ORDER BY POLICY.ID;

//2. Показати ID полісу, прізвище та імя клієнта, назву послуги та суму, яку потрібно сплатити за замовлення. Відсорт за ID полісу;
SELECT POLICY.ID, CUSTOMER.LASTNAME, CUSTOMER.FIRSTNAME, SERVICE.PRODUCT_NAME, (SERVICE.PRICE+IFNULL(POLICY.OVERPAY, 0))*IFNULL(100-CUSTOMER.DISCOUNT, 100)/100 AS COST
FROM POLICY, CUSTOMER, SERVICE
WHERE CUSTOMER_ID=CUSTOMER.ID 
AND SERVICE_ID=SERVICE.ID
GROUP BY POLICY.ID
ORDER BY POLICY.ID;

//3. Показати прізвище та імя страхових агентів та кількість замовлень, які вони виконали. Відсорт за ID агента; 
SELECT EMPLOYEE.LASTNAME, EMPLOYEE.FIRSTNAME, COUNT(*) AS NUMBER
FROM EMPLOYEE, POLICY
WHERE EMPLOYEE_ID=EMPLOYEE.ID
GROUP BY EMPLOYEE.ID
ORDER BY EMPLOYEE.ID;

//4. Показати прізвище та імя страхових агентів та суму всіх замовлень, які вони виконали. Відсорт за ID агента; 
SELECT EMPLOYEE.LASTNAME, EMPLOYEE.FIRSTNAME, (SERVICE.PRICE+IFNULL(POLICY.OVERPAY, 0))*IFNULL(100-CUSTOMER.DISCOUNT, 100)/100 AS COST
FROM EMPLOYEE, POLICY, SERVICE, CUSTOMER
WHERE EMPLOYEE_ID=EMPLOYEE.ID
AND CUSTOMER_ID=CUSTOMER.ID 
AND SERVICE_ID=SERVICE.ID
GROUP BY EMPLOYEE.ID
ORDER BY EMPLOYEE.ID;

//5. Показати прізвище та імя страхових агентів, сума всіх замовлень з 1 квітня, які вони виконали, більша 10000, та їх зарплатню з премією 2500грн. Відсорт за ID агента; 
SELECT EMPLOYEE.ID, EMPLOYEE.LASTNAME, EMPLOYEE.FIRSTNAME, EMPLOYEE.RATE+IFNULL(EMPLOYEE.BONUS, 0)+2500 AS SALARY
FROM EMPLOYEE, POLICY, SERVICE, CUSTOMER
WHERE EMPLOYEE_ID=EMPLOYEE.ID
AND CUSTOMER_ID=CUSTOMER.ID 
AND SERVICE_ID=SERVICE.ID
AND (SERVICE.PRICE+IFNULL(POLICY.OVERPAY, 0))*IFNULL(100-CUSTOMER.DISCOUNT, 100)/100>10000
AND DATE_START> '2022/03/30'
GROUP BY EMPLOYEE.ID
ORDER BY EMPLOYEE.ID;

//6. Показати кількість замовлень за 2022 рік та їх загальну суму;
SELECT COUNT(*) AS NUMBER, SUM((SERVICE.PRICE+IFNULL(POLICY.OVERPAY, 0))*IFNULL(100-CUSTOMER.DISCOUNT, 100)/100)  AS COST
FROM POLICY, SERVICE, CUSTOMER
WHERE CUSTOMER_ID=CUSTOMER.ID 
AND SERVICE_ID=SERVICE.ID
AND DATE_START > '2021/12/31';

//7. Показати кількість виплат за 2022 рік та їх загальну суму;
SELECT COUNT(*) AS NUMBER, SUM(((SERVICE.PRICE+IFNULL(POLICY.OVERPAY, 0))*IFNULL(100-CUSTOMER.DISCOUNT, 100)/100)/100*INSURANCASE.PAYMENT_PERCENT) AS PAYMENTS
FROM POLICY, SERVICE, CUSTOMER, PAYMENT, INSURANCASE
WHERE CUSTOMER_ID=CUSTOMER.ID 
AND SERVICE_ID=SERVICE.ID
AND POLICY_ID= POLICY.ID
AND INSURANCASE_ID=INSURANCASE.ID 
AND DATE_PAYMENT > '2021/12/31';

//8. Показати прізище та імя клієнтів, назву послуги, страхового випадку та дату його настання за 1 квартал 2022. Відсортувати за ID виплати;
SELECT CUSTOMER.LASTNAME, CUSTOMER.FIRSTNAME, SERVICE.PRODUCT_NAME, INSURANCASE.NAME, PAYMENT.DATE_INSURANCASE
FROM POLICY, CUSTOMER, SERVICE, PAYMENT, INSURANCASE
WHERE CUSTOMER_ID=CUSTOMER.ID 
AND SERVICE_ID=SERVICE.ID
AND POLICY_ID= POLICY.ID
AND INSURANCASE_ID=INSURANCASE.ID 
AND DATE_START BETWEEN '2022/01/30' AND '2022/04/01'
ORDER BY PAYMENT.ID;

//9. Показати назви страхових випадків та кількість їх настання серед клієнтів страхової компанії. Відсортувати за  ID виплати;
SELECT INSURANCASE.NAME, COUNT(*) AS NUMBER
FROM POLICY, INSURANCASE, PAYMENT
WHERE POLICY_ID= POLICY.ID
AND INSURANCASE_ID=INSURANCASE.ID 
GROUP BY INSURANCASE.NAME
ORDER BY PAYMENT.ID;

//10. Показати назви департаменту та кількість замовлень, які вони виконали. Відсортувати за назвою департаменту;
SELECT DEPARTMENT.NAME, COUNT(*) AS NUMBER
FROM DEPARTMENT, EMPLOYEE, POLICY
WHERE DEPARTMENT.ID=ID_DEPARTMENT
AND EMPLOYEE_ID=EMPLOYEE.ID
GROUP BY DEPARTMENT.NAME
ORDER BY DEPARTMENT.NAME;

//11. Показати місто та кількість замовлень, яке там виконали агенти. Відсортувати за містом;
SELECT DEPARTMENT.CITY, COUNT(*) AS NUMBER
FROM DEPARTMENT, EMPLOYEE, POLICY
WHERE DEPARTMENT.ID=ID_DEPARTMENT
AND EMPLOYEE_ID=EMPLOYEE.ID
GROUP BY DEPARTMENT.CITY
ORDER BY DEPARTMENT.CITY;

//12. Показати назви послуг та кількість клієнтів, які скористались нею. Відсортувати за ID послуги;
SELECT SERVICE.PRODUCT_NAME, COUNT(*) AS NUMBER
FROM SERVICE, POLICY
WHERE SERVICE_ID=SERVICE.ID
GROUP BY PRODUCT_NAME
ORDER BY SERVICE.ID;

//13. Показати прізвище та імя клієнтів та суму замовлення, яка менша за 700. Відсортувати за ID полісу;
SELECT POLICY.ID, CUSTOMER.LASTNAME, CUSTOMER.FIRSTNAME, (SERVICE.PRICE+IFNULL(POLICY.OVERPAY, 0))*IFNULL(100-CUSTOMER.DISCOUNT, 100)/100 AS COST
FROM POLICY, CUSTOMER, SERVICE
WHERE CUSTOMER_ID=CUSTOMER.ID 
AND SERVICE_ID=SERVICE.ID
AND (SERVICE.PRICE+IFNULL(POLICY.OVERPAY, 0))*IFNULL(100-CUSTOMER.DISCOUNT, 100)/100<700
ORDER BY POLICY.ID;

//14. Показати прізвище та імя клієнтів та назву послуги, поліс яких діє сьогодні. Відсортувати за ID полісу;
SELECT CUSTOMER.LASTNAME, CUSTOMER.FIRSTNAME, SERVICE.PRODUCT_NAME
FROM SERVICE, CUSTOMER, POLICY
WHERE CUSTOMER_ID=CUSTOMER.ID
AND SERVICE_ID=SERVICE.ID
AND DATE_START<'2022/05/21'
AND DATE_END>'2022/05/21'
ORDER BY POLICY.ID;

//15. Показати вид страхування та кількість разів його замовлення клієнтами. Відсортувати за ID послуги;
SELECT SERVICE.PRODUCT_TYPE, COUNT(*) AS NUMBER
FROM SERVICE, POLICY
WHERE SERVICE_ID=SERVICE.ID
GROUP BY PRODUCT_TYPE
ORDER BY SERVICE.ID;

